version: '3.4'

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  resource:
    restart: "no"
  migrations:
    restart: "no"
